lang: en-US
title: The MANTLE NETWORK Initiative
email: contact@themantlenetwork.org
description: An international collective of scientists studying the Earth’s mantle

baseurl: ""
url: "https://themantlenetwork.github.io"

author:
  name: The MANTLE NETWORK Initiative
  twitter:
  picture: 

twitter_username:
github_username:
logo: /assets/images/logo.png

search: true
search_full_content: true
search_provider:

algolia:
  application_id:
  index_name:
  search_only_api_key:
  powered_by:

collections:
  pages:
    output: true
    permalink: /:name/

remote_theme: mmistakes/jekyll-theme-basically-basic

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap